<a href="https://colab.research.google.com/github/Abdulhay04/Abdulhay04/blob/main/my_pandas_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 

In [ ]:
arr = np.random.rand(5)
arr

array([0.30786133, 0.79807564, 0.175919  , 0.54412859, 0.67604629])

In [ ]:
arr1 = np.random.randint(5)
arr1

0

In [ ]:
np.random.seed(1)
ind = np.random.randint(1, 5, 2)
ind.astype(int)

array([2, 4])

In [ ]:
ey = np.eye(4)
ey 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]], 
               [[7, 8, 9], 
                [10, 11, 12],
                [13, 14, 15]]])

In [ ]:
a3.ndim

3

In [ ]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6]])

In [ ]:
a2.ndim

2

In [ ]:
a3.shape

(2, 2, 3)

In [ ]:
a1 = np.array([1, 2, 3])
# a1.shape
a1.ndim

1

In [ ]:
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]], 
               [[7, 8, 9], 
                [10, 11, 12],
                [13, 14, 15]]])

In [ ]:
a3[:2, :3, :1]        # kesish

array([[[ 1],
        [ 4],
        [ 7]],

       [[ 7],
        [10],
        [13]]])

In [ ]:
a3[:, 2:, 2:]

array([[[ 9]],

       [[15]]])

In [ ]:
ran = np.arange(2, 20+2, 2, dtype = float)
ran

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [ ]:
a4 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a4.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a4.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a4.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a4.min()

1

In [ ]:
# mylist = [1, 2, 3, 45, 6, 8, 78, 23, 56, 7686, 123]
# print("The list is:")
# print(mylist)
random_elements = np.random.choice(1,10, 2)
print("The randomly selected elements are:")
print(random_elements)
  

The randomly selected elements are:
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
# import choice
import numpy as np
import matplotlib.pyplot as plt
  
# Using choice() method
gfg = np.random.choice(13, 5000)
  
count, bins, ignored = plt.hist(gfg, 25, density = False)
# plt.show()

In [ ]:
fig, ax = plt.subplots(figsize = (10, 6))
# plt.show()

In [ ]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize = (10, 6))


In [ ]:
mylist1 = [1, 2, 4, 5, 8, 6, 4, 6, 9, 3, 2, 5, 6, 3]
for i in range(len(mylist1)):
    if(mylist1[i] == 9):
        print(i)

8


In [ ]:

print(b'\xC2\xA9\x20\xF0\x9D\x8C\x86\x20\xE2\x98\x83'.decode('utf-8'))
print(b'\xC2\xA9\x20\xF0\x9D\x8C\x86\x20\xE2\x98\x83'.decode('latin-1'))

© 𝌆 ☃
© 𝌆 ☃


In [ ]:
l = [[[1, 2, 3], 
      [4, 5, 6]],
     [[7, 8, 9],
      [10, 11, 12]]]
l

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [ ]:
def func(x):
  if x == 1:
    return 1
  else:
    return x * func(x - 1)


print(func(5))

120


In [ ]:
rl = [1, 4, 6, 2, 3, 8, 9, 5, 7]
ls = []
s = 1
for i in range(len(rl)):
  if s == rl[i]:
    ls.append(i)
    s +=1
    continue
print(ls)

def qidir_va_top(x):
  rl = [1, 4, 6, 2, 3, 8, 9, 5, 7]



[0, 3, 4]


In [ ]:
import sys
A = [64, 25, 12, 22, 11]
 
for i in range(len(A)):
  
  min_idx = i
for j in range(i+1, len(A)):
  if A[min_idx] > A[j]:
   min_idx = j

A[i], A[min_idx] = A[min_idx], A[i]
 

for i in range(len(A)):
 print("%d" %A[i]),

Sorted array
11
12
22
25
64


In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
arr_mean = np.array(a)
arr_mean.mean()

5.25

In [ ]:
a_sum = sum(a)
print(a_sum/8)

4.5


In [ ]:
a_sml = a[0]
a_bg = a[-1]
a_median = (a_sml + a_bg) / 2
a_median

4.5

In [ ]:
var_lst = [1, 2, 3]                       # mean 2 ga teng
var_arr = np.array(var_lst)               # var 3 ga teng
var_arr.var()                             # natija 0.666

0.6666666666666666

In [ ]:
print(((1 - 2)**2 + (2 - 2)**2 + (3 - 2)**2)/3)

0.6666666666666666


In [ ]:
from flask import Flask

app = Flask(__name__)                 # bu doim turishi kerak
@app.route("/action")
def action():
    return "<p>action, World!</p>"
print(action())

<p>Hello, World!</p>


In [ ]:
def csv_fayl(url):
  rd = pd.read_csv(url)
  df = pd.DataFrame(rd)
  print(df.Genre)

url = 'https://storage.googleapis.com/qwasar-public/track-ds/imdb-movie-data.csv'
csv_fayl(url)

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...           
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object


In [ ]:
import pandas as pd

rd = pd.read_csv(url)
df = pd.DataFrame(rd)
print(df.columns)
    # return genre

# def action():
#     return action

# def adventure():
#     return adventure

# def comedy():
#     return comedy

# def drama():
#     return drama

# def romance():
#     return romance

url = 'https://storage.googleapis.com/qwasar-public/track-ds/imdb-movie-data.csv'


Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')


In [ ]:
from flask import Flask
import pandas as pd

url = 'https://storage.googleapis.com/qwasar-public/track-ds/imdb-movie-data.csv'
rd = pd.read_csv(url)
df = pd.DataFrame(rd)

app = Flask(__name__)

@app.route("/")
def get_genre():
  genre = df.Genre
  return genre
print(get_genre().head())

0     Action,Adventure,Sci-Fi
1    Adventure,Mystery,Sci-Fi
2             Horror,Thriller
3     Animation,Comedy,Family
4    Action,Adventure,Fantasy
Name: Genre, dtype: object
